[package]
name = "palpatine"
version = "0.1.0"
edition = "2021"

[dependencies]
path-clean = "1.0.1"
git2 = "0.16.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.95"
clap = { version = "4.1.13", features = ["cargo"] }